### ISSUE TITLE
Unable to Register student

### ISSUE THREAD

**Issue by IgorGee** [IgorGee/Attendance-Tracker#13]
@mgarod 
With proper parameters filled out, I am unable to register a student into the database.

5448fa7c13071a9c1a60eb677cee5ff12345cab2

**Comment by mgarod** [comment]
Any more info for me?

**Comment by mgarod** [comment]
When trying to register

java.lang.IllegalArgumentException: Sakas is not a valid Professor's name
	at Information.Professor.getProfessor(Professor.java:39)
	at GUI.RegistrationClassEntryBox.getEnrolledCourses(RegistrationClassEntryBox.java:89)
	at GUI.RegistrationWindow.registerNewStudent(RegistrationWindow.java:54)
	at GUI.RegistrationWindow.lambda$display$2(RegistrationWindow.java:36)
...

**Comment by IgorGee** [comment]
At the moment you must entire the full name of the Professor:

e.g. "William Sakas"
